### PR TITLE
updating your video list

### PR DESCRIPTION
**Pull request by raer6**
Hi there,

I was wondering if this live video course about GraphQL might be suitable for your list.

Thank you for your consideration,

Rada.

### CODE REVIEW

**Comment by dabit3** [comment]
Hey @raer6 this looks like a great course! Will you be using AWS AppSync as the API or will you be using it in the course?

**Comment by raer6** [comment]
Hi, thank you for your interest.

I will check out with the author and let you know.

Cheers!

**Comment by raer6** [comment]
Hi again!

The author let me know that AWS will not be covered in the course.

Cheers,

Rada.

**Comment by dabit3** [comment]
Hey @raer6, thanks for the PR. This repo will only be including content around AWS AppSync, but if anything changes please let me know!

**Pull request closed without merging**
